version: "3.9"

services:
  nazo_app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src:/app
    networks:
      - your-network

  nazo_web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8088:80
    depends_on:
      - nazo_app
    volumes:
      - ./src:/app
    networks:
      - your-network

  db:
    image: mysql:latest
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      TZ: 'Asia/Tokyo'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - your-network
      
volumes:
  db_data:

networks:
  your-network: